---
title: "linear model"
author: "Xinyuan Liu"
date: "11/16/2021"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

## load nyc airbnb data

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

## visualization

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price)) +
  geom_point()
```

## LET'S FIT A LINEAR MODEL

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
summary(fit)
summary(fit)$corf
fit %>% broom::tidy()
```

If you want to present output

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "borough", "Borough")) %>% select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)
```


```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = resid)) +
  geom_density() +
  xlim(-200, 200)
```

Let's try a different model

```{r}
fit = lm(price ~ stars*borough + room_type*borough, data = nyc_airbnb) ## looking at the interaction of star and borough and room type and borough

broom::tidy(fit)
```

Let's try nesting

```{r}
nyc_airbnb %>% 
  relocate(borough) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    lm_results = map(lm_fits, broom::tidy)
  ) %>% 
  select(borough, lm_results) %>% 
  unnest(lm_results) %>% 
  filter(term == "stars")
```

look at neighborhood in manhattan

```{r}
manhattan_lm_res = 
  nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  select(-borough) %>% 
  relocate(neighborhood) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~lm(price ~ stars + room_type, data = .x)),
    lm_results =map(lm_fits, broom::tidy)
  ) %>% 
  select(neighborhood, lm_results) %>% 
  unnest(lm_results)
```

```{r}
manhattan_lm_res %>% 
  filter(str_detect(term, "stars")) %>% 
  ggplot(aes(x = estimate)) +
  geom_density()

manhattan_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  
```

## logistic regression

```{r}
new_nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(expensive_apt = as.numeric(price >500)) 
```

let's fit a logistic regression for the binary outcome

```{r}
logistic_fit = 
  glm(
    expensive_apt ~ stars + borough, 
    data = new_nyc_airbnb,
    family = binomial()
)

logistic_fit %>%
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: "),
    estimate = exp(estimate),
    OR = estimate
  ) %>% 
  select(term, OR = estimate, p.value)
```

